INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '0peoilx83ryo', '02b9s2c0wid1', 32, 20, 85, 67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '10xoa7f68rzv', '1rde8opl5ap', 64, 91, 26, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '2y5c3rvhr7k', '288wchlvwoa', 0, 41, 63, 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '3e1hsmu0oxzm', '3tzpeztob8oh', 33, 75, 23, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '4qll8w7yyl1f', '4abkmhbcnq4s', 77, 29, 72, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '5ev2vv603crg', '5r8abtztu84f', 55, 37, 9, 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '6r0t3ojc47q', '6mg7gu3j5gnf', 30, 65, 27, 93, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '7n7obxmo06xo', '7cy05tr8rsot', 18, 11, 71, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '87dfe1fz9zo7', '85uw0lrrxlbp', 85, 25, 45, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO FOOD_NUTRIENT (
    COMPANY, FOOD, CALORIE, CARBOHYDRATE, PROTEIN, FAT, REG_DTM, UPD_DTM
) VALUES (
    '9cw50xkznzk', '9j4gu2aty97r', 79, 86, 39, 82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
