INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '0mems7769l5', '07z5papvhyn7', '0093tcce9f6xu', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '18oqrfzae2zf', '1s4r2lwhf12k', '1supbjsr7a6l', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '2hk36t0irwv9', '2kap2kfieth', '2vx5wybdxa5m', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '3gsxn83cp1dn', '39f260ptdkok', '3fxcbc1qgi68', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '4iawairi96e', '4mmpotnsnc5m', '4vepa4parlv', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '5iw1rmdkgpk8', '56g2m4xwzssw', '5x4hcqci8ue', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '6j9nan3qndrh', '6qlz6ey8hypb', '6265qokk2ls', '6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '79ty547b1na', '7e7lu6f0xb2p', '7idbm4zjmirk', '7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '8vy6hejkl8h9', '8745u09iua8', '8vjpn0kpey', '8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO PLAYLIST (
    GENRE, ARTIST, SONG_TITLE, USE_YN, REG_DTM, UPD_DTM
) VALUES (
    '9jtv5aw9gn3', '9pzj62qbkkpb', '9g4a8q4005i', '9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
