-- PLAYLIST Table Creation Script
DROP TABLE IF EXISTS PLAYLIST;

CREATE TABLE PLAYLIST (
    ID BIGSERIAL,
    GENRE VARCHAR(50),
    ARTIST VARCHAR(100),
    SONG_TITLE VARCHAR(200) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);